#!/bin/bash
# This script will Wipe a HDD with random data, up to DOD standards

set -eu

lsblk
echo "What drive do you want to prep?"
read drive
drive="/dev/${drive}"

# Wipe drive with random data
sudo cryptsetup open --type plain -d /dev/urandom $drive to_be_wiped

# Ensure the entire disk is wiped by writing random data 
sudo dd if=/dev/zero of=/dev/mapper/to_be_wiped bs=4M status=progress

# Close the cryptsetup device
sudo cryptsetup close to_be_wiped 

echo "Drive $drive has been prepped"
exit